[package]
name = "docan"
version = "0.1.0-alpha2"
edition = "2021"
license = "MIT OR GPL-3.0"
authors = ["zhuyu <zhuyu4839@gmail.com>"]
description = "A DoCAN protocol."
homepage = "https://github.com/zhuyu4839/ecu-proto-rs"
repository = "https://github.com/zhuyu4839/ecu-proto-rs"
keywords = [
    "automotive",
    "UDS",
    "DoCAN"
]

[dependencies]
log = "0.4"
thiserror = "2"
hex = "0.4"
iso15765-2 = "0.1.0-alpha1"
rs-can = "0.1.0-alpha3"

[dependencies.iso14229-1]
path = "../iso14229-1"
default-features = false
optional = true

#[dependencies.tokio]
#workspace = true
#features = ["time", ]
#optional = true

[features]
async = []

default = ["std2020", "client", "server"]

client = ["rs-can/isotp-std2004"]
server = ["rs-can/isotp-std2004"]

std2006 = ["iso14229-1/std2006"]
std2013 = ["iso14229-1/std2013"]
std2020 = ["iso14229-1/std2020"]
